config/routes.rb
InventorySystem::Application.routes.draw do
  resources :inventories
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :quantity
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  # before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  def index
    @inventories = Inventory.all
  end

  def show
    @inventory = Inventory.find(params[:id])
  end

  def new
    @inventory = Inventory.new
  end

  def edit
    @inventory = Inventory.find(params[:id])
  end

  def create
    @inventory = Inventory.new(inventory_params)
    if @inventory.save
      redirect_to @inventory, notice: 'Inventory was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @inventory = Inventory.find(params[:id])
    if @inventory.update(inventory_params)
      redirect_to @inventory, notice: 'Inventory was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy
      redirect_to @inventory
  end

  private
  def set_inventory
    @inventory = Inventory.find(params[:id])
  end
  def inventory_params
    params.require(:inventory).permit(:title, :description, :quantity)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= form_for :inventory, url: inventories_path do |f| %>
<% if @inventory.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this contact from being saved:</h2>

  <ul>
    <% @inventory.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>
<br>
<div>
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</div>
<br>
<div>
  <%= f.label :quantity %><br>
  <%= f.text_field :quantity %>
</div>
<br>
<div>
  <%= f.submit %>
</div>
<% end %>
<br>
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<h1>All The Inventory</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Quantity</th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.title %></td>
        <td><%= inventory.description %></td>
        <td><%= inventory.quantity %></td>
        <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= form_for :inventory, url: inventories_path do |f| %>

<% if @inventory.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this contact from being saved:</h2>

  <ul>
    <% @inventory.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>
<br>
<div>
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</div>
<br>
<div>
  <%= f.label :quantity %><br>
  <%= f.text_field :quantity %>
</div>
<br>
<div>
  <%= f.submit %>
</div>

<% end %>

<% link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p><%= notice %></p>

<p>
  <strong>Inventory:</strong>
  <%= @inventory.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @inventory.description %>
</p>
<p>
  <strong>Quantity:</strong>
  <%= @inventory.quantity %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InventorySystem</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>